name: My test
on: 
  push

jobs:
  job1:
    name: first job
    runs-on: ubuntu-latest
    steps:
      - name: first job steps
        uses: actions/checkout@v2
      - name: second job steps
        run: env | sort
        
  job2:
    name: second job
    runs-on: windows-latest
    steps: 
      - name: second job steps
        uses: actions/checkout@v2
      - name: second job steps
        run: "Get-ChildItem Env: | Sort-Object Name"
